export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const VALIDAR_FORMULARIO_EXITO = 'VALIDAR_FORMULARIO_EXITO';
export const VALIDAR_FORMULARIO_ERROR = 'VALIDAR_FORMULARIO_ERROR';

export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS';
export const DESCARGA_PRODUCTOS_EXITOSA = 'DESCARGA_PRODUCTOS_EXITOSA';
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR';

export const OBTENER_PRODUCTO_ELIMINAR = "OBTENER_PRODUCTO_ELIMINAR"
export const PRODUCTO_ELIMINAR_EXITO = "PRODUCTO_ELIMINAR_EXITO"
export const PRODUCTO_ELIMINAR_ERROR = "PRODUCTO_ELIMINAR_ERROR"

export const OBTENER_PRODUCTO_EDITAR = " OBTENER_PRODUCTO_EDITAR"
export const PRODUCTO_EDITAR_EXITO = "PRODUCTO_EDITAR_EXITO"
export const PRODUCTO_EDITAR_ERROR = "PRODUCTO_EDITAR_ERROR"